#!/usr/bin/env python3
from notmuch2 import Database
from datetime import datetime
import re

def unsnooze(db):
    now = datetime.now()
    for msg in db.messages("tag:snoozed"):
        print("Checking message: " + msg.header("Subject"))
        for tag in msg.tags:
            match = re.search('snoozed/until-([0-9]{8}-[0-9]{4})', tag)
            if match is not None:
                print("\tFound matching tag: " + match.group(1))
                try:
                    t = datetime.strptime(match.group(1), '%Y%m%d-%H%M')
                    print("\t\tUnsnooze date: " + str(t))
                    if t <= now:
                        print("Unsnoozing: " + msg.messageid)
                        with msg.frozen():
                            msg.tags.remove(tag)
                            msg.tags.remove("snoozed")
                            msg.tags.add("inbox")
                except ValueError as e:
                    # couldn't parse time, do nothing
                    # print("\t\t" + e)
                    pass

if __name__ == "__main__":
    with Database(mode=Database.MODE.READ_WRITE) as db:
        unsnooze(db)
