#!/usr/bin/env python
from notmuch import Query, Database
from datetime import datetime
import re

def unsnooze(db):
    now = datetime.now()
    for msg in Query(db, "tag:snoozed").search_messages():
        print("Checking message: " + msg.get_header("Subject"))
        for tag in msg.get_tags():
            match = re.search('snoozed([0-9]{8}-[0-9]{4})', tag)
            if match is not None:
                print("\tFound matching tag: " + match.group(1))
                try:
                    t = datetime.strptime(match.group(1), '%d%m%Y-%H%M')
                    print("\t\tUnsnooze date: " + str(t))
                    if t <= now:
                        print("Unsnoozing: " + msg.get_message_id())
                        msg.freeze()
                        msg.remove_tag(tag)
                        msg.remove_tag("snoozed")
                        msg.add_tag("inbox")
                        msg.thaw()
                except ValueError as e:
                    # couldn't parse time, do nothing
                    # print("\t\t" + e)
                    pass

if __name__ == "__main__":
    db = Database(mode=Database.MODE.READ_WRITE)
    unsnooze(db)
    db.close()

