#!/usr/bin/perl
use warnings;
use strict;

use Date::Manip;

# Tags changes to be performed. Will be applied verbatim when snoozing
# and inverted when message reappears.
my $tagchanges = "-inbox";

if ($#ARGV != 1) {
  die("USAGE: ./snooze-mail TIME QUERY");
}

my $time = $ARGV[0];
my $query = $ARGV[1];

# replace +Nm by +Nmin, since we rarely mean months by m.
$time =~ s/([0-9]+)m$/$1min/;

my $abstime = UnixDate($time, "%H:%M %m%d%Y");
`notmuch tag $tagchanges $query`;

# Invert tag changes:
$tagchanges =~ s/\+/-/g;
$tagchanges =~ s/-/+/g;

`echo 'notmuch tag $tagchanges $query' | at \"$abstime\" >/dev/null 2>&1`;

print "Snoozed until: ", UnixDate($time, "%c"), "\n";

# Local Variables:
# mode: cperl
# End:
